# Generated by Django 4.1.7 on 2023-04-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
