# Generated by Django 4.1.7 on 2023-04-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_fact_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='fact',
            new_name='facts',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='skill',
            new_name='skills',
        ),
        migrations.AlterField(
            model_name='about',
            name='birthday',
            field=models.DateField(),
        ),
    ]
