# Generated by Django 4.1.7 on 2023-04-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_rename_fact_about_facts_rename_skill_about_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumearea',
            name='title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
